version: '3.8'

services:
  api:
    build: .
    container_name: nestjs_api_otm
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    environment:
      DATABASE_URL: mongodb://root:otimizacaoderotas@mongodb:27017/otimizacaoDeRotas?authSource=admin
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017" 
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: otimizacaoderotas
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local