apiVersion: v1
kind: Service
metadata:
  name: nestjs-api-service
spec:
  type: NodePort 
  selector:
    app: nestjs-api-rotas
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 3000